export const MODULE_ID = 'daggerheart-death-moves';
export const SOCKET_NAME = `module.${MODULE_ID}`;

export const SOCKET_TYPES = {
    SHOW_UI: 'SHOW_UI',
    SHOW_SPECTATOR_UI: 'SHOW_SPECTATOR_UI',
    REMOVE_SPECTATOR_UI: 'REMOVE_SPECTATOR_UI',
    SHOW_ANNOUNCEMENT: 'SHOW_ANNOUNCEMENT',
    SHOW_BORDER: 'SHOW_BORDER',
    REMOVE_BORDER: 'REMOVE_BORDER',
    HIDE_UNSELECTED: 'HIDE_UNSELECTED',
    FLOW_COMPLETE: 'FLOW_COMPLETE'
};